"""Initial migration with dynamic DB URL

Revision ID: a276b0fe17f8
Revises: 
Create Date: 2024-09-19 01:13:09.782582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a276b0fe17f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streets_id'), 'streets', ['id'], unique=False)
    op.create_table('street_lights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_street_lights_id'), 'street_lights', ['id'], unique=False)
    op.create_table('cost_and_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('installation_cost', sa.Float(), nullable=True),
    sa.Column('bulb_cost', sa.Float(), nullable=True),
    sa.Column('fixture_cost', sa.Float(), nullable=True),
    sa.Column('electricity_cost', sa.Float(), nullable=True),
    sa.Column('maintenance_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_and_pricing_id'), 'cost_and_pricing', ['id'], unique=False)
    op.create_table('energy_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('average_daily_consumption', sa.Float(), nullable=True),
    sa.Column('average_monthly_consumption', sa.Float(), nullable=True),
    sa.Column('operating_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_consumption_id'), 'energy_consumption', ['id'], unique=False)
    op.create_table('hardware_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('pole_type', sa.String(), nullable=True),
    sa.Column('pole_height', sa.Float(), nullable=True),
    sa.Column('control_system_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_information_id'), 'hardware_information', ['id'], unique=False)
    op.create_table('installation_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_details_id'), 'installation_details', ['id'], unique=False)
    op.create_table('issue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.String(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('time_to_resolve', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_reports_id'), 'issue_reports', ['id'], unique=False)
    op.create_table('life_cycle_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('expected_lifespan', sa.Integer(), nullable=True),
    sa.Column('replacement_schedule', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_cycle_information_id'), 'life_cycle_information', ['id'], unique=False)
    op.create_table('light_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('bulb_type', sa.String(), nullable=True),
    sa.Column('bulb_manufacturer', sa.String(), nullable=True),
    sa.Column('wattage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_light_specifications_id'), 'light_specifications', ['id'], unique=False)
    op.create_table('maintenance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=True),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_history_id'), 'maintenance_history', ['id'], unique=False)
    op.create_table('operational_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('last_status_update', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_status_id'), 'operational_status', ['id'], unique=False)
    op.create_table('warranty_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_light_id', sa.Integer(), nullable=True),
    sa.Column('component_name', sa.String(), nullable=True),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('warranty_terms', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['street_light_id'], ['street_lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warranty_information_id'), 'warranty_information', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warranty_information_id'), table_name='warranty_information')
    op.drop_table('warranty_information')
    op.drop_index(op.f('ix_operational_status_id'), table_name='operational_status')
    op.drop_table('operational_status')
    op.drop_index(op.f('ix_maintenance_history_id'), table_name='maintenance_history')
    op.drop_table('maintenance_history')
    op.drop_index(op.f('ix_light_specifications_id'), table_name='light_specifications')
    op.drop_table('light_specifications')
    op.drop_index(op.f('ix_life_cycle_information_id'), table_name='life_cycle_information')
    op.drop_table('life_cycle_information')
    op.drop_index(op.f('ix_issue_reports_id'), table_name='issue_reports')
    op.drop_table('issue_reports')
    op.drop_index(op.f('ix_installation_details_id'), table_name='installation_details')
    op.drop_table('installation_details')
    op.drop_index(op.f('ix_hardware_information_id'), table_name='hardware_information')
    op.drop_table('hardware_information')
    op.drop_index(op.f('ix_energy_consumption_id'), table_name='energy_consumption')
    op.drop_table('energy_consumption')
    op.drop_index(op.f('ix_cost_and_pricing_id'), table_name='cost_and_pricing')
    op.drop_table('cost_and_pricing')
    op.drop_index(op.f('ix_street_lights_id'), table_name='street_lights')
    op.drop_table('street_lights')
    op.drop_index(op.f('ix_streets_id'), table_name='streets')
    op.drop_table('streets')
    # ### end Alembic commands ###
